// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeRkQDMrkRgNiBci5eWgbVc3yfP0zRUoY',
    appId: '1:446137425134:web:2fabc0f1f9cf92f415e7ff',
    messagingSenderId: '446137425134',
    projectId: 'smart-helmet-e736f',
    authDomain: 'smart-helmet-e736f.firebaseapp.com',
    storageBucket: 'smart-helmet-e736f.firebasestorage.app',
    measurementId: 'G-003Z9MQ9J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhxZEtHCRQwjFopBOIM4uBpa3owNNs-8A',
    appId: '1:446137425134:android:89169f610272241715e7ff',
    messagingSenderId: '446137425134',
    projectId: 'smart-helmet-e736f',
    storageBucket: 'smart-helmet-e736f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqvW6xYfEcAL2oyz_ZJV2qR0Q2J1pOM-s',
    appId: '1:446137425134:ios:066cb964a72dd7fd15e7ff',
    messagingSenderId: '446137425134',
    projectId: 'smart-helmet-e736f',
    storageBucket: 'smart-helmet-e736f.firebasestorage.app',
    iosBundleId: 'com.example.smartHelmetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqvW6xYfEcAL2oyz_ZJV2qR0Q2J1pOM-s',
    appId: '1:446137425134:ios:066cb964a72dd7fd15e7ff',
    messagingSenderId: '446137425134',
    projectId: 'smart-helmet-e736f',
    storageBucket: 'smart-helmet-e736f.firebasestorage.app',
    iosBundleId: 'com.example.smartHelmetApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeRkQDMrkRgNiBci5eWgbVc3yfP0zRUoY',
    appId: '1:446137425134:web:e85ec603cc32fb6f15e7ff',
    messagingSenderId: '446137425134',
    projectId: 'smart-helmet-e736f',
    authDomain: 'smart-helmet-e736f.firebaseapp.com',
    storageBucket: 'smart-helmet-e736f.firebasestorage.app',
    measurementId: 'G-H062E1ZEXF',
  );
}
