org.gradle.jvmargs=-Xmx384M -XX:MaxMetaspaceSize=128m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
flutter.experimental.impeller=false
kotlin.incremental=false
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=false
org.gradle.caching=false

