name: smart_helmet_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  provider: ^6.1.1
  flutter_blue_plus: ^1.31.0
  shared_preferences: ^2.2.3
  fl_chart: ^0.68.0
  flutter_tts: ^4.0.2
  geolocator: ^10.1.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.6.5
  http: ^0.13.5
  url_launcher: ^6.2.6

  tflite_flutter: ^0.12.1
  fftea: ^1.5.0+1


  # kept once, higher version
  pdf: ^3.11.1             # kept once, higher version
  printing: ^5.13.3        # kept once, higher version
    # kept once, higher version


  flutter_bluetooth_serial: ^0.4.0

  permission_handler: ^11.3.1
  collection: ^1.18.0
  sensors_plus: ^4.0.2
  vibration: ^2.0.0

  cupertino_icons: ^1.0.8
  firebase_database: ^11.3.10
  google_maps_flutter: ^2.9.0
  google_sign_in: ^6.2.1

  flutter_staggered_animations: ^1.1.1
  percent_indicator: ^4.2.3

  screenshot: ^3.0.0

  path_provider: ^2.1.5
  share_plus: ^12.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/eeg_stress_model_final.tflite
    - assets/route_risk_model.tflite
    - assets/icons/motorcycle.png
    - assets/icons/app_icon.png
    - assets/icons/g-logo.png
    - assets/model.tflite
    - assets/icons/dev_team.png
    - assets/eeg_stress_model_float32.tflite
    - assets/post_journey_risk_model.tflite
    - assets/risk_thresholds.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"