// lib/services/danger_zone_service.dart
//
// Runs the danger_zone_model.tflite to classify each sensor reading
// as SAFE (0) or DANGER (1), then clusters danger GPS points into
// "danger zones" for rendering on the JourneyReportScreen map.
//
// Model features (12 total — must match train_danger_zone_model.py):
//   [0]  accelX
//   [1]  accelY
//   [2]  accelZ
//   [3]  gyroX
//   [4]  gyroY
//   [5]  gyroZ
//   [6]  speedKmh
//   [7]  turnRateDegPerSec   = |gyroZ|
//   [8]  accelMagnitude      = sqrt(ax²+ay²+az²)
//   [9]  lateralAccel        = |accelY|
//   [10] brakeForce          = max(0, −accelX)
//   [11] speedRisk           = speedKmh / 120

import 'dart:math';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:tflite_flutter/tflite_flutter.dart';
import '../models/journey_model.dart';

/// A danger zone — a GPS location that the model flagged as dangerous.
class DangerZone {
  final LatLng center;
  final double radiusMeters;
  final double dangerScore;   // 0.0–1.0 (model confidence)
  final String label;         // e.g. "Sharp Turn", "Hard Brake"

  DangerZone({
    required this.center,
    required this.radiusMeters,
    required this.dangerScore,
    required this.label,
  });
}

class DangerZoneService {
  Interpreter? _interpreter;
  bool _isLoaded = false;

  // ─── Scaler constants from danger_zone_scaler.txt ────────────────────────
  // Generated by train_danger_zone_model.py — update if model is retrained.
  static const List<double> _means = [
    -0.7409425569656487,   // accelX
    -0.01519877839356286,  // accelY
     9.805502662479878,    // accelZ
     0.1372854804982271,   // gyroX
    -0.17681905498127526,  // gyroY
     0.7094147880604287,   // gyroZ
    52.02872980630398,     // speedKmh
    50.29021784690391,     // turnRateDegPerSec
    10.124928941190243,    // accelMagnitude
     0.9470118706925559,   // lateralAccel
     0.930467762751152,    // brakeForce
     0.4335727484887466,   // speedRisk
  ];

  static const List<double> _stddevs = [
     1.9083881886342007,   // accelX
     1.5609654208753456,   // accelY
     0.6544021056655018,   // accelZ
    10.29451788354216,     // gyroX
     9.971125432588435,    // gyroY
    83.39030043074224,     // gyroZ
    25.234752121370132,    // speedKmh
    66.5232249983563,      // turnRateDegPerSec
     0.8304961471520661,   // accelMagnitude
     1.2409724270911788,   // lateralAccel
     1.7654871302993285,   // brakeForce
     0.21028960112933803,  // speedRisk
  ];

  static const double _threshold = 0.5;

  // ─── Load model from Flutter assets ──────────────────────────────────────

  Future<void> loadModel() async {
    if (_isLoaded) return;
    try {
      _interpreter = await Interpreter.fromAsset('assets/danger_zone_model.tflite');
      _isLoaded = true;
    } catch (e) {
      _isLoaded = false;
    }
  }

  bool get isLoaded => _isLoaded;

  // ─── Feature engineering (mirrors the Python add_derived_features) ────────

  List<double> _buildFeatures({
    required double accelX,
    required double accelY,
    required double accelZ,
    required double gyroX,
    required double gyroY,
    required double gyroZ,
    required double speedKmh,
  }) {
    final turnRate    = gyroZ.abs();
    final accelMag    = sqrt(accelX * accelX + accelY * accelY + accelZ * accelZ);
    final lateralAcc  = accelY.abs();
    final brakeForce  = (-accelX).clamp(0.0, double.infinity);
    final speedRisk   = speedKmh / 120.0;

    return [
      accelX, accelY, accelZ,
      gyroX, gyroY, gyroZ,
      speedKmh,
      turnRate, accelMag, lateralAcc, brakeForce, speedRisk,
    ];
  }

  // ─── Standardise ─────────────────────────────────────────────────────────

  List<double> _standardise(List<double> raw) {
    return List.generate(
      raw.length,
      (i) => (raw[i] - _means[i]) / _stddevs[i],
    );
  }

  // ─── Run single inference ─────────────────────────────────────────────────

  /// Returns danger score 0.0–1.0, or null if model not ready.
  double? predict({
    required double accelX, required double accelY, required double accelZ,
    required double gyroX,  required double gyroY,  required double gyroZ,
    required double speedKmh,
  }) {
    if (!_isLoaded || _interpreter == null) return null;

    final raw = _buildFeatures(
      accelX: accelX, accelY: accelY, accelZ: accelZ,
      gyroX: gyroX, gyroY: gyroY, gyroZ: gyroZ,
      speedKmh: speedKmh,
    );
    final scaled = _standardise(raw);

    final input  = [scaled.map((v) => v.toDouble()).toList()];
    final output = List.generate(1, (_) => List<double>.filled(1, 0.0));
    _interpreter!.run(input, output);

    return output[0][0].clamp(0.0, 1.0);
  }

  // ─── Rule-based label ────────────────────────────────────────────────────

  String _labelFromSensors({
    required double accelX,
    required double gyroZ,
    required double speedKmh,
  }) {
    if (gyroZ.abs() > 150) return 'Risky Turn';
    if (gyroZ.abs() > 100) return 'Sharp Turn';
    if (-accelX > 3.0)     return 'Emergency Brake';
    if (-accelX > 1.5)     return 'Hard Brake';
    if (speedKmh > 80)     return 'High Speed Zone';
    return 'Danger Zone';
  }

  // ─── Analyse a full ride ──────────────────────────────────────────────────
  //
  // Iterates over every SensorReading that has a GPS fix and runs the model.
  // Returns a list of DangerZone objects to render as circles on the map.
  //
  // We also include TurnEvents and BrakingEvents as guaranteed danger points.

  Future<List<DangerZone>> analyseRide(JourneyData journey) async {
    await loadModel();

    final List<DangerZone> zones = [];

    // 1. Run model on all sensor readings that have a GPS fix
    for (final reading in journey.sensorReadings) {
      // SensorReadings only have lat/lng if they were added with GPS position
      // We check the GPS track for the nearest timestamp instead
      final gpsPoint = _nearestGpsPoint(journey.gpsTrack, reading.timestamp);
      if (gpsPoint == null) continue;
      if (gpsPoint.latitude == 0.0 && gpsPoint.longitude == 0.0) continue;

      final score = predict(
        accelX: reading.accelX, accelY: reading.accelY, accelZ: reading.accelZ,
        gyroX: reading.gyroX,  gyroY: reading.gyroY,  gyroZ: reading.gyroZ,
        speedKmh: gpsPoint.speedKmh,
      );

      if (score != null && score >= _threshold) {
        zones.add(DangerZone(
          center: LatLng(gpsPoint.latitude, gpsPoint.longitude),
          radiusMeters: 25 + score * 35,   // 25–60 m based on confidence
          dangerScore: score,
          label: _labelFromSensors(
            accelX: reading.accelX,
            gyroZ: reading.gyroZ,
            speedKmh: gpsPoint.speedKmh,
          ),
        ));
      }
    }

    // 2. Add turn events as guaranteed danger zones
    for (final event in journey.turnEvents) {
      if (event.latitude == 0.0 && event.longitude == 0.0) continue;
      final score = event.severity == 'risky' ? 0.92 : 0.72;
      zones.add(DangerZone(
        center: LatLng(event.latitude, event.longitude),
        radiusMeters: event.severity == 'risky' ? 40 : 30,
        dangerScore: score,
        label: event.severity == 'risky' ? 'Risky Turn' : 'Sharp Turn',
      ));
    }

    // 3. Add braking events as guaranteed danger zones
    for (final brake in journey.brakingEvents) {
      if (brake.latitude == 0.0 && brake.longitude == 0.0) continue;
      zones.add(DangerZone(
        center: LatLng(brake.latitude, brake.longitude),
        radiusMeters: brake.severity == 'emergency' ? 45 : 30,
        dangerScore: brake.severity == 'emergency' ? 0.95 : 0.75,
        label: brake.severity == 'emergency' ? 'Emergency Brake' : 'Hard Brake',
      ));
    }

    // 4. Merge overlapping zones (cluster within 30 m)
    return _clusterZones(zones, clusterRadiusM: 30);
  }

  // ─── Nearest GPS point by timestamp ──────────────────────────────────────

  GpsPoint? _nearestGpsPoint(List<GpsPoint> track, DateTime ts) {
    if (track.isEmpty) return null;
    GpsPoint? best;
    int bestDiff = 999999999;
    for (final p in track) {
      if (p.timestamp == null) continue;
      final diff = (p.timestamp!.difference(ts).inMilliseconds).abs();
      if (diff < bestDiff) {
        bestDiff = diff;
        best = p;
      }
    }
    return bestDiff < 10000 ? best : null; // only within 10 s
  }

  // ─── Cluster overlapping zones ────────────────────────────────────────────

  List<DangerZone> _clusterZones(List<DangerZone> zones, {double clusterRadiusM = 30}) {
    if (zones.isEmpty) return [];

    final List<DangerZone> merged = [];
    final List<bool> used = List.filled(zones.length, false);

    // Sort by danger score descending so higher-confidence zones absorb lower
    final sorted = List<DangerZone>.from(zones)
      ..sort((a, b) => b.dangerScore.compareTo(a.dangerScore));

    for (int i = 0; i < sorted.length; i++) {
      if (used[i]) continue;
      final anchor = sorted[i];
      double sumLat   = anchor.center.latitude;
      double sumLng   = anchor.center.longitude;
      double maxScore = anchor.dangerScore;
      double maxRadius = anchor.radiusMeters;
      int    count    = 1;

      for (int j = i + 1; j < sorted.length; j++) {
        if (used[j]) continue;
        final dist = _haversineM(
          anchor.center.latitude, anchor.center.longitude,
          sorted[j].center.latitude, sorted[j].center.longitude,
        );
        if (dist <= clusterRadiusM) {
          used[j] = true;
          sumLat  += sorted[j].center.latitude;
          sumLng  += sorted[j].center.longitude;
          count++;
          if (sorted[j].dangerScore  > maxScore)  maxScore  = sorted[j].dangerScore;
          if (sorted[j].radiusMeters > maxRadius) maxRadius = sorted[j].radiusMeters;
        }
      }

      merged.add(DangerZone(
        center: LatLng(sumLat / count, sumLng / count),
        radiusMeters: maxRadius,
        dangerScore: maxScore,
        label: anchor.label,
      ));
    }

    return merged;
  }

  // ─── Haversine distance in metres ────────────────────────────────────────

  double _haversineM(double lat1, double lon1, double lat2, double lon2) {
    const r = 6371000.0;
    final dLat = _rad(lat2 - lat1);
    final dLon = _rad(lon2 - lon1);
    final a = sin(dLat / 2) * sin(dLat / 2) +
        cos(_rad(lat1)) * cos(_rad(lat2)) * sin(dLon / 2) * sin(dLon / 2);
    return r * 2 * atan2(sqrt(a), sqrt(1 - a));
  }

  double _rad(double deg) => deg * pi / 180;

  void dispose() {
    _interpreter?.close();
    _interpreter = null;
    _isLoaded = false;
  }
}
